### PR TITLE
Ruby's naming convention

### PR DESCRIPTION
**Pull request by renanbona**
* Fix a misspelling
* Add link about ruby's naming convention

### CODE REVIEW

**Comment by florianjosefreheis** [comment]
@renanbona cheers for the misspelling, I already found a couple of others so will look at this over the weekend.

**Comment by florianjosefreheis** [comment]
Hi @renanbona ,
snippets look fine. May I ask you to read the following page about how to use the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and to create a new PR? It would be great if we could use the same process as 30-Seconds-of-Knowledge. I will write a contribution guide asap.

**Comment by florianjosefreheis** [comment]
Hi @renanbona, just merged your other PR. Can you follow the Gitflow for this PR as well? Cheers.

**Comment by renanbona** [comment]
Sure @florianjosefreheis. Sorry for the delay, but I just created a new pull request following the Gitflow. Cheers.

**Comment by florianjosefreheis** [comment]
@renanbona awesome, thx. Closing this PR as covered by https://github.com/florianjosefreheis/30-seconds-of-ruby/pull/12

**Pull request closed without merging**
