### PR TITLE
Splat operators

### PR DESCRIPTION
**Pull request by renanbona**
* Add splat operators content to README
* Create splat_operators.md

### CODE REVIEW

**Comment by florianjosefreheis** [comment]
thx @renanbona will have a look over the weekend.

**Comment by florianjosefreheis** [comment]
Hi @renanbona, 
snippets looks fine. May I ask you to read the following page about how to use the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and to create a PR aligned with it? It would be great if we could use the same process as 30-Seconds-of-Knowledge. I will write a contribution guide asap.

**Comment by florianjosefreheis** [comment]
Hi @renanbona,
Just wanted to check in with you and see if you have any questions regarding the Gitflow.

**Comment by renanbona** [comment]
Sorry the delay. I just opened a new pull request for the development branch.

**Comment by florianjosefreheis** [comment]
@renanbona thx, just merged it. I guess we can close that one.

**Pull request closed without merging**
