### PR TITLE
Lambdas vs Procs

### PR DESCRIPTION
**Pull request by renanbona**
* Add lambda vs procs snippet
* Add lambda vs procs content on README

### CODE REVIEW

**Comment by florianjosefreheis** [comment]
Hi @renanbona, great effort for all of your PR. May I ask you to follow the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) for all of your PRs? Thx

**Comment by florianjosefreheis** [comment]
Hi @renanbona, any update regarding the above? cheers

**Comment by renanbona** [comment]
I'm really sorry for the delay. But I created a new PR with all the snippets I wrote on the others PR's. Thanks for the opportunity for being part of this amazing project.

**Comment by florianjosefreheis** [comment]
@renanbona closing this PR as covered by https://github.com/florianjosefreheis/30-seconds-of-ruby/pull/12

**Pull request closed without merging**
