### PR TITLE
Enumerable snippets

### PR DESCRIPTION
**Pull request by dieggofaustino**

### CODE REVIEW

**Review by renanbona — APPROVED** [review]
Excellent snippets! Could you also update the README with those?

**Comment by dieggofaustino** [comment]
Sure.

**Comment by florianjosefreheis** [comment]
@dieggofaustino amazing, I will have a look over the weekend. Please wait as I want to introduce the Gitflow Workflow for contributors.
@renanbona thx for helping out here

**Comment by dieggofaustino** [comment]
No problem @florianjosefreheis, thank you

**Comment by florianjosefreheis** [comment]
Hi @dieggofaustino,
snippets look fine. May I ask you to read the following page about how to use the Gitflow Workflow and to create a PR aligned with it? It would be great if we could use the same process as 30-Seconds-of-Knowledge. I will write a contribution guide asap.

**Comment by dieggofaustino** [comment]
So as I understand I have just to open a new PR for the development branch instead of master, right?

**Comment by florianjosefreheis** [comment]
@dieggofaustino yep, branch of your feature_banch from the development branch. When finished, merge with development branch. The last step is to open a PR to the origin development branch. So we can keep track of all the changes.
More info about the Gitflow Workflow [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).
You can close the other PR afterward.

**Pull request closed without merging**
